Review treatment of issued at, issuer, audience #16
reaktivity/nukleus-oauth.spec pull request #8
Opened 2019-06-18 23:08 UTC by dknoma

Added a few more tests for testing with `iss` and `aud` claims, as well as changing existing tests to support the new feature (no `iss` or `aud` claims are treated as nulls).

2019-06-19 06:28 UTC, jfallows submitted a review, later dismissed
Looks great!

We'll also want to add `resolveEx` to `OAuthFunctions` to layout the `issuer` and `audience`, but what you have right now is fine to get started.

2019-06-19 21:57 UTC, dknoma commented
I successfully created another file, `TooManyRealmsKeys.jwk`, with the test realms specifically for the too many realms tests and all tests are passing. Changed the `fails.too.many.realms` controller and nukleus scripts to now use the correct kids `[realm1, realm2, ..., realm17TooMany]`.

2019-06-20 23:47 UTC, dknoma commented
> Looks great!
> 
> We'll also want to add `resolveEx` to `OAuthFunctions` to layout the `issuer` and `audience`, but what you have right now is fine to get started.

So instead of using the regular `claims` method, we'll want `resolveEx` to add the `iss` and `aud` claims for us?

2019-06-21 14:15 UTC, jfallows submitted a review, later dismissed
Once the dependencies are ready, this looks good to merge.

2019-06-27 17:53 UTC, jfallows requested changes

2019-06-27 17:53 UTC, jfallows commented on src/main/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthJwtKeys.java
> +        RFC7515_ES256 = esKeyPair;
Recommend changing to simpler form:
```
        try
        {
            RFC7515_RS256 = initRSAKeyPair(rsa256);
            RFC7515_ES256 = initECKeyPair(es256);
        }
        catch(Exception ex)
        {
            throw new IllegalStateException(ex);
        }
```

2019-06-27 17:53 UTC, jfallows commented on src/main/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthJwtKeys.java
> +        Map<String, String> params) throws Exception
Make sure the `throws` exception type is as specific as possible, not just generic `Exception`.
Please apply this feedback to all such `throws` in the method signatures called from this method too, same for `initECKeyPair`.

2019-06-27 17:53 UTC, jfallows commented on src/main/scripts/org/reaktivity/specification/nukleus/oauth/control/resolve/one.realm.with.issuer.and.audience/controller.rpt
> +              .build()}
Each `.` should be vertically aligned with the `:` for readability.
Please apply that approach to all scripts.

2019-06-27 17:53 UTC, jfallows commented on src/test/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthJwtKeysTest.java
> +
Needed?

2019-06-27 17:53 UTC, jfallows commented on src/main/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthFunctions.java
> +        return helperFactory.get();
No need to populate a `helperFactories` map, just need to `return new JwtHelper(pair, kind, algorithm)` directly.

2019-06-27 18:53 UTC, jfallows requested changes

2019-06-27 18:53 UTC, jfallows commented on src/main/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthJwtKeys.java
> +        Map<String, String> params) throws NoSuchAlgorithmException, InvalidKeySpecException
Simplify to `GeneralSecurityException` which is a common super type for these exceptions.
Please apply to all similar method signatures.

2019-06-27 18:53 UTC, jfallows commented on src/main/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthJwtKeys.java
> +        catch(Exception ex)
Change catch to `GeneralSecurityException` if it is sufficient to cover all the cases.

2019-06-27 18:53 UTC, jfallows commented on src/test/java/org/reaktivity/specification/nukleus/oauth/internal/OAuthFunctionsTest.java
> +    @Test(expected = RuntimeException.class)
Why is this not getting a `GeneralSecurityException` instead?

2019-06-27 19:29 UTC, jfallows approved these changes

2019-06-27 20:58 UTC, merged